Revert "Added printing headers to requests..."
This reverts commit b138970d05ed4e199a36a1a6dedbbbdd686c76b8.

The reason is that the commit was raising exceptions:

Exception happened during processing of request from ('127.0.0.1', 45989)
Traceback (most recent call last):
  File "/usr/lib/python2.5/SocketServer.py", line 464, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.5/SocketServer.py", line 254, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.5/SocketServer.py", line 522, in __init__
    self.handle()
  File "./proxy", line 50, in handle
    self.__base_handle()
  File "/usr/lib/python2.5/BaseHTTPServer.py", line 316, in handle
    self.handle_one_request()
  File "/usr/lib/python2.5/BaseHTTPServer.py", line 310, in handle_one_request
    method()
  File "./proxy", line 76, in do_CONNECT
    self._read_write(soc, 300)
  File "./proxy", line 147, in _read_write
    end_headers = re.search('(\r\n\r\n)', local_data).span()[0]
AttributeError: 'NoneType' object has no attribute 'span'